### ISSUE TITLE
Gnome platform version 40 is EOL

### ISSUE THREAD

**Issue by ProjectSynchro** [flathub/io.github.Soundux#37]
You might want to bump the gnome runtime version to avoid support issues.

**Comment by D3SOX** [comment]
Is it just a bump without any migration? I'll see if I can test this tomorrow

**Comment by ProjectSynchro** [comment]
It should be as quick as a bump but it appears there are some build issues (on my end as well)
See this CI run: https://github.com/flathub/io.github.Soundux/pull/36

Digging deeper makes it look like the git history for https://github.com/Soundux/guardpp was wiped, and the commit that is referenced by the 'guardpp' [submodule](https://github.com/Soundux/Soundux/tree/0.2.7/lib) in the 0.2.7 tag does not exist anymore. (https://github.com/Soundux/guardpp/tree/51816d2f7eeebf99cee0c0e8ea1f1acbc9f6800c), unfortunately the dist tarball does not include any of the git submodules.

Other than that (which is definitely blocking), it appears that bumping all the relevant dependencies works without issue in version 42 of the SDK. This build issue is not related to bumping the SDK version as building the flatpak as-is also fails.

This might be down to some verification step when using cmake to build a flatpak and due to the mismatch of git commits the build fails.
