### ISSUE TITLE
Incompatibility with gtk3-nocsd?

### ISSUE THREAD

**Issue by D3SOX** [flathub/io.github.Soundux#74]
Originally posted on Discord

Ubuntu 22.04.4 LTS
Intel® Core™ i76700K CPU @ 4.00GHz × 8
NVIDIA Corporation GM204 [GeForce GTX 970]
X11

I recently did an update for Soundux (flatpak) that showed up and it caused Soundux to white screen and I haven't been able to resolve this issue.

When I launch Soundux through flatpak in terminal with `flatpak run io.github.Soundux`, I receive the following:

```
$ flatpak run io.github.Soundux 
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[17:15:53] [success] Config read
[17:15:53] [success] LibWnck found - Icon support is enabled
[17:15:53] [message] PulseAudio is ready!
[17:15:53] [success] Unloaded left over module 52
[17:15:53] [success] Unloaded left over module 53
[17:15:53] [success] Unloaded left over module 54
[17:15:53] [success] Unloaded left over module 55
[17:15:53] [success] Unloaded left over module 56
[17:15:53] [message] Using DISPLAY :99.0
Gtk-Message: 10:15:53.961: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:15:53.961: Failed to load module "unity-gtk-module"
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Gtk-Message: 10:15:54.128: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:15:54.128: Failed to load module "unity-gtk-module"
Gtk-Message: 10:15:54.128: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:15:54.128: Failed to load module "unity-gtk-module"
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1280x720: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1280x720: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1280x720: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
[17:15:54] [warning] Could not find proccess with id 1
[17:15:54] [warning] Could not find proccess with id 2

(soundux:2): GLib-CRITICAL **: 10:15:54.632: Source ID 414 was not found when attempting to remove it
```

and an accompanying window opens with a white screen and everything just hangs.

I have
- reinstalled `gtk3-nocsd`
- reinstalled `libgtk3-nocsd0`
- added `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0` to ~/.bashrc
- installed `libcanberra-gtk-module`
- installed `unity-gtk3-module`

Rebooted a few times post installations

**Comment by D3SOX** [comment]
@ProjectSynchro Tagging you here because you might have some insights as you've worked on this

**Comment by ProjectSynchro** [comment]
Interesting, looks like there is a missing permission that is required for that specific library.

I'll spin up an Ubuntu 22.04 VM and see if I can reproduce. 

All libraries should be pulled in from the runtime.. weird..

**Comment by ProjectSynchro** [comment]
On a fresh Ubuntu 22.04 install, I was able to run the Soundux flatpak without any issues:
![Screenshot_20240325_224814](https://github.com/flathub/io.github.Soundux/assets/5131712/a52ae516-1e18-497e-9bb1-0b62a2b3fbaa)

The warnings about "canberra-gtk-module" and "unity-gtk-module" are benign.

It looks like there are issues with the version of libwebkitgtk in the Gnome 44 runtime and the NVIDIA proprietary driver: https://bugs.webkit.org/show_bug.cgi?id=254807

This may be related to their NVIDIA hardware, does Soundux work if they run: `flatpak run --env=WEBKIT_DISABLE_DMABUF_RENDERER=1 io.github.Soundux`?

Additionally it may help if they update their drivers, check for any flatpak updates, and run `flatpak repair`.

**Comment by D3SOX** [comment]
Thanks for the investigation. Waiting for confirmation to close this

**Comment by D3SOX** [comment]
Upstream issue with NVIDIA drivers. If anyone stumbles upon this issue add the environment variable` WEBKIT_DISABLE_DMABUF_RENDERER=1` to fix.
